version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb-spinit
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass123
    command: --auth
